version: '3.6'

services:  
  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    volumes:
      - /data/db
    ports:
      - "27017:27017"
    networks: 
      - file-service-network
  minio:
    image: "minio/minio"
    container_name: minio
    volumes:
      - "C:/minio/data"
    command: ["server", "/data"]
    ports:
      - "9000:9000"
    networks:
      - file-service-network
    environment:
      MINIO_ACCESS_KEY: Q3AM3UQ867SPQQA43P2F
      MINIO_SECRET_KEY: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  fileserviceapi:
    image: "fileserviceapi"
    container_name: fileserviceapi
    ports:
      - "51230:80"
    networks: 
        - file-service-network  

networks:
  opus-network:
    name: file_service_network
    driver: bridge

# If you get an error - "ERROR: for fileserviceapi  Cannot start service fileserviceapi: 
#                        driver failed programming external connectivity on endpoint test.fileserviceapi (...):
#                        Error starting userland proxy: Bind for 0.0.0.0:51230: unexpected error Permission denied"
#
# Follow these steps:
# 1. Stop all the running containers in Docker:  docker stop $(docker ps -a -q)
# 2. Stop Docker on your machine.
# 3. Restart your machine & Docker